In [11]:
import numpy as np

%time

data = np.random.randn(2,3)
data

Wall time: 0 ns


array([[-1.42518421, -2.75730163,  0.40259406],
       [ 0.65837439, -1.46602395,  1.49158572]])

In [12]:
data*10

array([[-14.25184211, -27.57301626,   4.02594056],
       [  6.58374389, -14.66023955,  14.91585722]])

In [13]:
data+data

array([[-2.85036842, -5.51460325,  0.80518811],
       [ 1.31674878, -2.93204791,  2.98317144]])

In [31]:
data-data

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [32]:
1/data

array([[-0.70166368, -0.36267342,  2.48389161],
       [ 1.51889262, -0.68211709,  0.67042744]])

In [34]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [1]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr_slice[:] = 67
arr_second = arr[:2]
arr_second[:] = 99
arr

array([99, 99,  2,  3,  4, 67, 67, 67,  8,  9])

In [11]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
names == 'Bob'
data[names=='Bob']

array([[-0.82607099,  1.5265866 , -0.07221217,  0.51663131],
       [ 0.15664222,  1.375595  ,  1.12352269,  1.01260038]])

In [12]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [13]:
data

array([[-0.82607099,  1.5265866 , -0.07221217,  0.51663131],
       [-0.05216407, -1.57791088,  0.03084484, -0.01864109],
       [-1.58724791,  1.04573544,  0.30392222,  0.17163962],
       [ 0.15664222,  1.375595  ,  1.12352269,  1.01260038],
       [-0.21623466, -0.27220776, -1.7269036 ,  2.06690414],
       [ 0.1785439 , -0.16289658,  1.18808025,  0.29567268],
       [ 1.24678238,  0.4452552 ,  0.95354354,  0.97518349]])

In [14]:
data[~(names=='Bob')]

array([[-0.05216407, -1.57791088,  0.03084484, -0.01864109],
       [-1.58724791,  1.04573544,  0.30392222,  0.17163962],
       [-0.21623466, -0.27220776, -1.7269036 ,  2.06690414],
       [ 0.1785439 , -0.16289658,  1.18808025,  0.29567268],
       [ 1.24678238,  0.4452552 ,  0.95354354,  0.97518349]])

In [15]:
data[data<0]=0

In [17]:
data[names != 'Joe'] =7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  0.03084484,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.1785439 ,  0.        ,  1.18808025,  0.29567268],
       [ 1.24678238,  0.4452552 ,  0.95354354,  0.97518349]])

In [18]:
arr = np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [19]:
arr[[2,4,6]]

array([[ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.]])

In [20]:
arr =np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
arr = np.random.randn(7)*5
arr

array([ 3.72175615, -2.36989587,  4.45597462,  3.0863287 ,  5.60127437,
       -5.37655017, -1.13984665])

In [22]:
a,b=np.modf(arr)
a

array([ 0.72175615, -0.36989587,  0.45597462,  0.0863287 ,  0.60127437,
       -0.37655017, -0.13984665])

In [23]:
b

array([ 3., -2.,  4.,  3.,  5., -5., -1.])